name: Nightly

# Download of the Photon DB is super slow (graphhopper server is the bottleneck).
# We don't want to block our CI/CD pipeline with this and daily updates are also not really required.
# Therefore, we switch to a weekly update cycle (and a time where we probably don't need our CI/CD pipleline anyway).
on:
  schedule:
    - cron: '0 7 * * 7'

jobs:
  publish-deutschland-main:
    uses: ./.github/workflows/publish.yaml
    with:
      context: .
      registry: bikenow.vkw.tu-dresden.de
      image: ${{ github.repository }}-deutschland
      branch: main
    secrets:
      NEXUS_DOCKER_PUB_USERNAME: ${{ secrets.NEXUS_DOCKER_PUB_USERNAME }}
      NEXUS_DOCKER_PUB_PASSWORD: ${{ secrets.NEXUS_DOCKER_PUB_PASSWORD }}

  publish-deutschland-stable:
    uses: ./.github/workflows/publish.yaml
    with:
      context: .
      registry: bikenow.vkw.tu-dresden.de
      image: ${{ github.repository }}-deutschland
      branch: stable
    secrets:
      NEXUS_DOCKER_PUB_USERNAME: ${{ secrets.NEXUS_DOCKER_PUB_USERNAME }}
      NEXUS_DOCKER_PUB_PASSWORD: ${{ secrets.NEXUS_DOCKER_PUB_PASSWORD }}

  publish-deutschland-release:
    uses: ./.github/workflows/publish.yaml
    with:
      context: .
      registry: bikenow.vkw.tu-dresden.de
      image: ${{ github.repository }}-deutschland
      branch: release
    secrets:
      NEXUS_DOCKER_PUB_USERNAME: ${{ secrets.NEXUS_DOCKER_PUB_USERNAME }}
      NEXUS_DOCKER_PUB_PASSWORD: ${{ secrets.NEXUS_DOCKER_PUB_PASSWORD }}
